### ISSUE TITLE
Double-clicking a result affects subsequent single-click

### ISSUE THREAD

**Issue by bronson** [t9md/atom-project-find-navigation#3]
Normally, when I single-click on find results, the results window remains focused.  However, if I double-click a result and then focus the find results again, the very next single-click will behave like a double-click.  After that, single-clicks go back to normal.

To reproduce:
- produce some project find results
- single-click on a few.  focus stays on the project find results tab
- double-click one of them
- click back into the project find results
- now single-click another result.  bam!  you get taken away.

Love this plugin, and this issue is really minor.

**Comment by t9md** [comment]
Oh, I could reproduce issue thanks for very easy to understand explanation.
Will check to fix, by the way I didn't notice since I mainly use this package via keymap, not mouse.

**Comment by t9md** [comment]
Fix this. Issue was happened when your activePane is not same pane as resultsPane.

Plus I disabled 'dblclick' event, since distinguishing 'mousedown' and 'dblclick' correctly need additional code and don't want to go far from original project-find to easy-to-track in future-change.

Mainly this package is focusing keyboard navigation, so in my opinion making mouse UI richier is out of scope of this package.

**Comment by bronson** [comment]
Fix looks good!  Agreed, dblclick often confuses users and developers simultaneously.  I sure won't miss it.
